name: Dev Docker Build

on:
  workflow_dispatch:  # Manual trigger

env:
  IMAGE_NAME: wealthplan-dp-dev
  AWS_ACCOUNT_ID: 287034252540
  AWS_REGION: eu-central-1

jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Compute ECR_REPO
        run: |
          echo "ECR_REPO=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:dev-latest -f docker/dev.Dockerfile .

      - name: Tag Docker image for ECR
        run: docker tag $IMAGE_NAME:dev-latest $ECR_REPO:dev-latest

      - name: Push Docker image to ECR
        run: docker push $ECR_REPO:dev-latest
